config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root 'previewer#index'
  post 'previewer/process_url', as: 'process_url'
  get 'previewer/preview', as: 'preview'
  mount Sidekiq::Web => '/sidekiq'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/preview.rb
class Preview < ApplicationRecord
  validates :url, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/previewer_controller.rb
class PreviewerController < ApplicationController
  def index; end

  def process_url
    url = params[:url]

    if valid_url?(url)
      UrlProcessingJob.perform_later(url)
    else
      flash[:error] = "Invalid URL format"
      redirect_to root_path
    end
  end

  private

  def valid_url?(url)
    uri = URI.parse(url)
    uri.is_a?(URI::HTTP) && !uri.host.nil?
  rescue URI::InvalidURIError
    false
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GraphPreviewerByLuna</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  </head>

  <body>
    <% if flash[:error] %>
      <div class="alert alert-danger">
        <%= flash[:error] %>
      </div>
    <% end %>

    <% if flash[:notice] %>
      <div class="alert alert-success">
        <%= flash[:notice] %>
      </div>
    <% end %>
    
    <%= yield %>

  </body>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</html>

app/views/previewer/index.html.erb
<div class="container py-5">
  <header class="text-white text-center py-5">
      <h1 class="display-4">Open Graph Preview By Luna</h1>
      <p class="lead mb-0">Paste web page url</p>
      <p class="mb-5 font-weight-light">to see the magic</p>
      <img src="https://bootstrapious.com/i/snippets/sn-img-upload/image.svg" alt="" width="150" class="mb-4">
  </header>

  <div class="row py-4">
    <%= form_with url: process_url_path, method: :post, remote: true, html: { id: 'url_form' } do |form| %>
        <%= form.text_field :url, placeholder: 'Enter URL', required: true, class: ' input-group mb-3 px-3 py-3 rounded-pill bg-white shadow-sm form-control mb-3' %>
          <div class="text-center">
            <%= form.submit 'Preview', class: 'btn btn-primary mb-3' %>
          </div>
    <% end %>

    <p class="font-italic text-white text-center">The image uploaded will be rendered inside the box below.</p>
    <div id="img_url" class="image-area text-center mt-4">
            <% if @preview %>
              <% if @preview.image_url %>
                <img src="<%= @preview.image_url %>" alt="Preview Image" class="img-fluid" style="max-width: 100%; max-height: 100%;">
              <% else %>
                <p>No Open Graph image found for the given URL.</p>
              <% end %>
            <% end %>
        <img id="imageResult" src="#" alt="" class="img-fluid rounded shadow-sm mx-auto d-block"></div>

    </div>
  </div>
</div>